name: Build the Pandoc container

on:
  workflow_dispatch:

jobs:
  build_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: ghcr login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: docker build
        run: docker build -t ghcr.io/${{ github.repository_owner }}/pandoc:latest .
      - name: docker push
        run: docker push ghcr.io/${{ github.repository_owner }}/pandoc:latest
